---

- name: DEPLOY SNMP CONFIGURATIONS
  hosts: ios
  gather_facts: no
  connection: local

  tasks:
    - name: DEPLOY SNMP COMMANDS WITHIN PLAYBOOK
      ios_config:
        commands:
          - snmp-server community public123 RO
          - snmp-server community networkallme RO
          - snmp-server community private123 RW
          - snmp-server location NTC_HQ_NBO
          - snmp-server contact STEVEN
        username: "{{ un }}"
        password: "{{ pwd }}"
        host: "{{ inventory_hostname }}"

