---

- name: DEPLOY SNMP CONFIGURATIONS
  hosts: ios
  gather_facts: no
  connection: local




  tasks:
    - name: DEPLOY SNMP COMMANDS WITHIN PLAYBOOK
      ios_config:
        commands:
          - snmp-server community public123 RO
          - snmp-server community networkallme RO
          - snmp-server community private123 RW
          - snmp-server location NTC_HQ_NBO
          - snmp-server contact STEVEN
        provider: "{{ ios_provider }}"

    - name: DEPLOY SNMP COMMANDS From configuration file
      ios_config:
        src: "./configs/snmp.cfg"
        provider: "{{ ios_provider }}"

    - name: DEPLOY SNMP COMMANDS From Jinja2 template
      ios_config:
        src: "./templates/snmp.j2"
        provider: "{{ ios_provider }}"